# Generated by Django 4.0.4 on 2022-04-28 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booktbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('posted_date_time', models.DateTimeField(auto_now_add=True, verbose_name='posted on')),
                ('book_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/uploadimg/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='genretbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='volumetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_no', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.booktbl')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.genretbl')),
            ],
        ),
        migrations.AddField(
            model_name='booktbl',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.genretbl'),
        ),
        migrations.AddField(
            model_name='booktbl',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
