# Generated by Django 4.0.4 on 2022-04-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_booktbl_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumetbl',
            name='type_id',
        ),
        migrations.AddField(
            model_name='booktbl',
            name='book',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='static/pdfs/', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='volumetbl',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.genretbl'),
        ),
    ]
